package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/ServerManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u152/9742/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, September 14, 2017 2:32:48 AM PDT
*/

public interface ServerManagerOperations  extends com.sun.corba.se.spi.activation.ActivatorOperations, com.sun.corba.se.spi.activation.LocatorOperations
{
} // interface ServerManagerOperations
